main: com.amoebaman.blocklobber.BlockLobber

name: BlockLobber
version: 1.4 (CB 1.4.5-R1.0)
author: AmoebaMan
description: Allows players to throw blocks

commands:

  lob:
    aliases: [lobblock, blocklobber]
    description: Lobs a block
    usage: /lob <ID[:data]> <strength>
    permission: blocklobber.lob
    permissions-message: You dont have the permission to lob blocks!
    
  lobs:
    aliases: [lobpreset, lobset]
    description: Defines a preset for lobbing blocks
    usage: |
           /lobs (mat|data|str) <value>
           /lobs <dir>
           /lobs <pos> [X] [Y] [Z] [world]
    permission: blocklobber.preset
    permissions-message: You dont have the permission to use lobber presets!
    
  lobc:
    aliases: [lobclear]
    description: Clears a previously defined preset
    usage: /lobc (pos|dir|mat|data|str|all)
    permission: blocklobber.preset
    permissions-message: You dont have the permission to use lobber presets!
    
  lobp:
    aliases: [lobprojectile, lobproj]
    description: Lobs a projectile
    usage: /lobp <type> <strength>
    permission: blocklobber.projectile.lob
    permissions-message: You dont have the permission to lob projectiles!
    
  lobps:
    aliases: [lobpresetp, lobsetp, lobsp]
    description: Defines a preset for lobbing projectile
    usage: |
           /lobps (type|str) <value>
           /lobps <dir>
           /lobps <pos> [X] [Y] [Z] [world]
    permission: blocklobber.projectile.preset
    permissions-message: You dont have the permission to use projectile presets!
    
  lobpc:
    aliases: [lobclearp, lobcp]
    description: Clears a previously defined projectile preset
    usage: /lobpc (pos|type|data|str)
    permission: blocklobber.projectile.preset
    permissions-message: You dont have the permission to use projectile presets!
    
  lobsv:
    aliases: [lobpresetview, lobsetview, lobsview, lobvs]
    description: View your presets
    usage: /lobsv
    permission: blocklobber.preset.view
    permissions-message: You dont have the permission to view your presets!
    
  lobr:
    aliases: [lobreload]
    description: reloads config
    usage: /lobr
    permission: blocklobber.reload
    permissions-messages: You dont have the permission to reload config!
    
permissions:

  blocklobber.lob:
    description: Allows players to lob blocks
    default: op
    
  blocklobber.preset:
    description: Allows players to set presets for lobbing blocks
    default: op
    
  blocklobber.projectile.lob:
    description: Allows players to lob projectiles
    default: op
    
  blocklobber.projectile.preset:
    description: Allows players to lob projectiles
    default: op
      
  blocklobber.preset.view:
    description: Allows players to use /lobvs
    default: op
    
  blocklobber.preset.view.block:
    description: Allows players to view block presets
    default: op
  
  blocklobber.preset.view.projectile:
    description: Allows players to view projectile presets
    default: op
    
  blocklobber.reload:
    description: Allows players to reload config
    default: op

  blocklobber.admin:
    description: Grants all admin permissions
    children: 
      blocklobber.reload: true
  
  blocklobber.block:
    description: Grants all block lobbing permissions
    children:
      blocklobber.lob: true
      blocklobber.preset: true
      blocklobber.preset.view: true
      blocklobber.preset.view.block: true
      
  blocklobber.projectile:
    description: Grants all projectile lobbing permissions
    children:
      blocklobber.projectile.lob: true
      blocklobber.projectile.preset: true
      blocklobber.preset.view: true
      blocklobber.preset.view.projectile: true
    
  blocklobber.*:
    description: Grants all permissions
    children:
      blocklobber.lob: true
      blocklobber.preset: true
      blocklobber.projectile.lob: true
      blocklobber.projectile.preset: true
      blocklobber.preset.view: true
      blocklobber.preset.view.block: true
      blocklobber.preset.view.projectile: true
      blocklobber.reload: true
